# Generated by Django 4.1.7 on 2023-03-08 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
