# Generated by Django 4.1.7 on 2023-03-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_alter_sprint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_points',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='ticket_number',
            field=models.PositiveIntegerField(),
        ),
    ]
