# Generated by Django 4.1.7 on 2023-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0005_alter_story_story_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
