# Generated by Django 4.1.7 on 2023-03-14 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_remove_planning_sprint_remove_pokerround_story_and_more'),
        ('sprint', '0007_sprint_planning_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='planning_id',
        ),
        migrations.AddField(
            model_name='sprint',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.planning'),
        ),
    ]
