# Generated by Django 4.1.7 on 2023-03-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0008_remove_sprint_planning_id_sprint_planning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='planning',
        ),
    ]
