# Generated by Django 4.1.7 on 2023-07-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0009_remove_sprint_planning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
