# Generated by Django 4.1.7 on 2023-03-08 19:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint')),
            ],
            options={
                'db_table': 'plannings',
            },
        ),
        migrations.CreateModel(
            name='PokerRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('avg_points', models.IntegerField()),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.planning')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.story')),
            ],
            options={
                'db_table': 'poker_rounds',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('avg_points', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poker_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.pokerround')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.CreateModel(
            name='PlanningParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.planning')),
            ],
            options={
                'db_table': 'planning_participants',
            },
        ),
    ]
