# Generated by Django 4.1.7 on 2023-03-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='avg_points',
            new_name='estimated_points',
        ),
    ]
