# Generated by Django 4.1.7 on 2023-03-13 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_vote_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
