# Generated by Django 4.1.7 on 2023-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_planning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerround',
            name='avg_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='estimated_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
