# Generated by Django 4.1.7 on 2023-03-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_alter_vote_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='pokerround',
            name='story',
        ),
        migrations.AddField(
            model_name='planning',
            name='sprint_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pokerround',
            name='story_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
