# Generated by Django 4.1.7 on 2023-03-14 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0009_remove_sprint_planning'),
        ('planning', '0007_remove_planning_sprint_remove_pokerround_story_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='sprint_id',
        ),
        migrations.RemoveField(
            model_name='pokerround',
            name='story_id',
        ),
        migrations.AddField(
            model_name='planning',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint'),
        ),
        migrations.AddField(
            model_name='pokerround',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.story'),
        ),
        migrations.AlterField(
            model_name='pokerround',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.planning'),
        ),
    ]
