# Generated by Django 4.1.7 on 2023-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_remove_planning_sprint_id_remove_pokerround_story_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerround',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
