# Generated by Django 4.1.7 on 2023-03-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_pokerround_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerround',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
