# Generated by Django 4.1.7 on 2023-07-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_alter_pokerround_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
