name: Generate PlantUML Diagrams
on:
  push:
    #branches:
    #  - 'main'
    paths:
      - '**.puml'
  workflow_dispatch:
    inputs:
      force_refresh:
        description: 'Force diagram refresh'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get modified UML files
        if: ${{ contains(inputs.force_refresh, 'no') || github.event_name == 'push' }}
        id: getmodified
        run: |
          git diff -r ${{ github.sha }}^1...${{ github.sha }} --name-status \
          | awk -F' ' '{
            if ( $1 !~ /^D$/ && $2 ~ /\.puml$/ && $2 !~ /(theme|config)\.puml$/ )
            {
              files = files " " $2
            }
          }
          END { printf "::set-output name=files::%s\n", files }
          '
      - name: Get all UML files (Force refresh)
        if: ${{ contains(inputs.force_refresh, 'yes') }}
        id: getall
        run: |
          git ls-files '*.puml' \
          | awk -F' ' '{
            if ($1 !~ /(theme|config)\.puml$/ )
            {
              files = files " " $1
            }
          }
          END { printf "::set-output name=files::%s\n", files }
          '
      - name: UML files to process
        if: ${{ contains(inputs.force_refresh, 'no') || github.event_name == 'push' }}
        run: |
          echo ${{ steps.getmodified.outputs.files }}
      - name: UML files to process
        if: ${{ contains(inputs.force_refresh, 'yes') }}
        run: |
          echo ${{ steps.getall.outputs.files }}

      - name: Generate SVG Diagrams
        if: ${{ contains(inputs.force_refresh, 'no') || github.event_name == 'push' }}
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg -o "../out" ${{ steps.getmodified.outputs.files }}
      - name: Generate SVG Diagrams
        if: ${{ contains(inputs.force_refresh, 'yes') }}
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg -o "../out" ${{ steps.getall.outputs.files }}

      - name: Generate PNG Diagrams
        if: ${{ contains(inputs.force_refresh, 'no') || github.event_name == 'push' }}
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng -o "../out" ${{ steps.getmodified.outputs.files }}
      - name: Generate PNG Diagrams
        if: ${{ contains(inputs.force_refresh, 'yes') }}
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng -o "../out" ${{ steps.getall.outputs.files }}

      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "[AUTO] Render PlantUML diagrams"
          branch: ${{ github.head_ref }}
          repository: